name: 'Issue Manager Action'
description: 'Automates certain tasks related to managing issues for CAE-Física.'
author: 'totallynotdavid'

inputs:
  org:
    description: 'GitHub Organization'
    required: true
  repo:
    description: 'GitHub Repository'
    required: true
  branch:
    description: 'Branch where ISSUE_TEMPLATE is located'
    required: true
  templateName:
    description: 'Name of the issue template'
    required: true
  issuePrefix:
    description: 'Prefix for the issue'
    required: true
  gifURL:
    description: 'URL of the gif to embed in comments'
    required: false
  useGif:
    description: 'Decide if gifURL should be used. Provide true or false.'
    required: true
    default: 'true'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'black'