name: 💼 Administración de Issues

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'
  pull_request_target:
    types:
      - opened

jobs:
  issueBot:
    name: 🤖 issueBot para GH Issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Actualizar GH Issues
        uses: totallynotdavid/Issue-Manager-Action@latest
        with:
          org: 'totallynotdavid'
          repo: 'Issue-Manager-Action'
          branch: 'master'
          template_name: 'mock_template.yml'
          issue_prefix: '[📚]:'
          gif_url: 'https://media.tenor.com/t8ZbssN1A9kAAAAd/momo-twice.gif'
        env:
          ISSUE_TOKEN: ${{ secrets.ISSUE_TOKEN }}
